name: boardview
description: This is a custom Flutter widget that can create a draggable BoardView or also known as a kanban. The view can be reordered with drag and drop.
version: 0.2.1
homepage: https://github.com/jakebonk/FlutterBoardView

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  pull_to_refresh: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
